# Generated by Django 5.1.4 on 2026-03-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meters", "0002_add_ikedc_aba_disco_providers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meterprofile",
            name="disco",
            field=models.CharField(
                choices=[
                    ("IBEDC", "Ibadan Electricity Distribution Company"),
                    ("EKEDC", "Eko Electricity Distribution Company"),
                    ("IKEDC", "Ikeja Electric"),
                    ("PHED", "Port Harcourt Electricity Distribution Company"),
                    ("BEDC", "Benin Electricity Distribution Company"),
                    ("EEDC", "Enugu Electricity Distribution Company"),
                    ("ABA", "Aba Electricity Distribution Company"),
                    ("AEDC", "Abuja Electricity Distribution Company"),
                    ("JED", "Jos Electricity Distribution Company"),
                    ("KAEDCO", "Kaduna Electric"),
                    ("KEDCO", "Kano Electricity Distribution Company"),
                    ("YEDC", "Yola Electricity Distribution Company"),
                ],
                max_length=20,
            ),
        ),
    ]
