# Generated by Django 5.1.4 on 2026-02-23 05:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('meter_number', models.CharField(max_length=20)),
                ('disco', models.CharField(choices=[('IBEDC', 'Ibadan Electricity Distribution Company'), ('EKEDC', 'Eko Electricity Distribution Company'), ('AEDC', 'Abuja Electricity Distribution Company'), ('PHED', 'Port Harcourt Electricity Distribution Company'), ('EEDC', 'Enugu Electricity Distribution Company'), ('BEDC', 'Benin Electricity Distribution Company'), ('KAEDCO', 'Kaduna Electric'), ('JED', 'Jos Electricity Distribution Company'), ('YEDC', 'Yola Electricity Distribution Company'), ('KANO', 'Kano Electricity Distribution Company')], max_length=20)),
                ('meter_owner_name', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_gateway', models.CharField(blank=True, choices=[('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave')], max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Payment Successful'), ('FAILED', 'Payment Failed'), ('EXPIRED', 'Payment Expired')], default='PENDING', max_length=10)),
                ('gateway_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('token_status', models.CharField(choices=[('PENDING', 'Pending Token'), ('DELIVERED', 'Token Delivered'), ('FAILED', 'Token Generation Failed'), ('RESENT', 'Token Resent')], default='PENDING', max_length=10)),
                ('token_value_encrypted', models.TextField(blank=True)),
                ('disco_reference', models.CharField(blank=True, max_length=255)),
                ('token_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resend_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_resend_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='meters.meterprofile')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='transaction_user_id_ced08a_idx'), models.Index(fields=['payment_status', 'token_status'], name='transaction_payment_2c50b0_idx'), models.Index(fields=['disco', '-created_at'], name='transaction_disco_c9631b_idx')],
            },
        ),
    ]
